# Sample workflow for building and deploying a Next.js app


name: CICD pipeline

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  

jobs:
   build-test-lint:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

       # 2. Setup Node.js (using Node 20 for stability)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

       # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run ESLint
      - name: Run Linter
        run: npm run lint

      # 5. Run Jest tests (CI mode + JUnit report)
      - name: Run Unit Tests
        run: npm run test
        env:
          CI: true

      # 6. Upload test results (JUnit XML)
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-results
          path: reports/junit/jest-junit.xml

      # 7. Build the Next.js app
      - name: Build Next.js project
        run: npm run build

          

